In [ ]:
import numpy as np
from hmmlearn import hmm


## Part 1: Train an HMM

In [ ]:
 # Number of hidden states (e.g., 0: Sunny, 1: Rainy)
n_states = 2
# Number of observable actions (e.g., 0: Walk, 1: Shop, )
n_observations = 3 

In [ ]:
# 1. Define Training Data (sequence of observations)
train_obs = np.array([[0], [1], [2], [0], [1], [1], [2], [0], [0], [1]])

# 2. Create a new HMM instance for learning
# We only specify the number of states; parameters will be learned
model = hmm.CategoricalHMM(n_components=n_states, n_iter=100, random_state=42)

# 3. Fit the model 
model.fit(train_obs)


--- Fitting Model to Data ---
Learned Transition Matrix:
 [[0.826 0.174]
 [1.    0.   ]]

Learned Emission Matrix:
 [[0.233 0.511 0.255]
 [0.997 0.001 0.002]]


In [8]:
print("Learned Transition Matrix:\n", np.round(learn_model.transmat_, 3))
print("\nLearned Emission Matrix:\n", np.round(learn_model.emissionprob_, 3))


Learned Transition Matrix:
 [[0.826 0.174]
 [1.    0.   ]]

Learned Emission Matrix:
 [[0.233 0.511 0.255]
 [0.997 0.001 0.002]]


## Part 2

In [10]:
n_states = 2 
n_observations = 3 

start_prob = np.array([0.6, 0.4])

# P(next_state | current_state)
trans_prob = np.array([
  [0.7, 0.3], # Sunny -> (Sunny, Rainy)
  [0.4, 0.6]  # Rainy -> (Sunny, Rainy)
])

# P(observation | state)
emit_prob = np.array([
  [0.6, 0.3, 0.1], # Sunny: (Walk, Shop, Clean)
  [0.1, 0.4, 0.5]  # Rainy: (Walk, Shop, Clean)
])

In [11]:
model = hmm.CategoricalHMM(n_components=n_states, random_state=42)

model.startprob_ = start_prob
model.transmat_ = trans_prob
model.emissionprob_ = emit_prob

In [12]:
# Example: Walk, Shop, Clean, Walk -> [0, 1, 2, 0]
obs_seq = np.array([[0], [1], [2], [0]]) 
# Must be 2D: (n_samples, n_features=1)

In [13]:
logprob, hidden_states = model.decode(obs_seq, algorithm="viterbi")

In [14]:
print("--- Using Defined Model ---")
print("Observation sequence (numeric):", obs_seq.flatten())
print("Most likely hidden states (numeric):", hidden_states) # 0: Sunny, 1: Rainy
print(f"Log Probability of sequence: {logprob:.4f}")


--- Using Defined Model ---
Observation sequence (numeric): [0 1 2 0]
Most likely hidden states (numeric): [0 1 1 0]
Log Probability of sequence: -5.7730
